
@startuml
'https://plantuml.com/sequence-diagram

actor "Doctor" as Employee
participant ":System" as System

activate Employee

    Employee -> System : requests list of operation requisitions
    activate System

        System --> Employee : asks for filtering constraints
    deactivate System

    Employee -> System : types desired filter options (e.g. patient name, operation type)
    activate System

        System --> Employee : displays operation success
    deactivate System
@enduml