name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
